name: Radicalize
on:
  workflow_dispatch:

jobs:
  radicalize:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile

      - name: Prepare gh CLI
        run: | 
          gh alias set repos "$(cat ./gh-alias-repos.txt)"
          echo ${{ secrets.DXOS_ACCESS_TOKEN }} | gh auth login --with-token
      - name: Generate a list of dxos repositories
        run: ./repo-list.sh dxos
        working-directory: ./scripts

      - name: Prepare the repositories for importing into radicle
        run: ./repo-migrate.js
        working-directory: ./scripts
      - name: Build packages
        run: ./build-packages.sh
        working-directory: ./scripts

      - name: Upload packages metadata
        uses: actions/upload-artifact@v2
        with:
          name: packages-list
          path: ./scripts/gen/*.txt

      - name: Remove redundant files from bundle before uploading
        run: rm -r ./**/{.git,node_modules}
        working-directory: ./scripts/gen/packages
      - name: Upload the packages bundle
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: ./scripts/gen/packages
