name: Radicalize
on:
  push:

jobs:
  radicalize:
    timeout-minutes: 180
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile

      - name: Prepare gh CLI
        run: | 
          git config --global user.email "npm@dxos.org"
          git config --global user.name "DXOS"
          gh alias set repos "$(cat ./gh-alias-repos.txt)"
          echo ${{ secrets.DXOS_ACCESS_TOKEN }} | gh auth login --with-token

          git config --global credential.helper store
          echo "https://${{ secrets.DXOS_ACCESS_TOKEN }}:x-oauth-basic@github.com" > "${HOME}/.git-credentials"
      - name: Generate a list of dxos repositories
        run: ./repo-list.sh dxos
        working-directory: ./scripts

      - name: Prepare the repositories for importing into radicle
        run: GITHUB_ACCESS_TOKEN="${{ secrets.DXOS_ACCESS_TOKEN }}" ./repo-migrate.js
        working-directory: ./scripts
      - name: Build packages
        run: |
          cp gen.package.json gen/package.json
          ./build-packages.sh
        working-directory: ./scripts

      - name: Display the count of building/failing packages
        run: wc -l ./*.txt
        working-directory: ./scripts/gen
      - name: Upload packages metadata
        uses: actions/upload-artifact@v2
        with:
          name: packages-list
          path: ./scripts/gen/*.txt

      - name: Remove redundant files from bundle before uploading
        run: rm -r ./**/{.git,node_modules}
        working-directory: ./scripts/gen/packages
      - name: Upload the packages bundle
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: ./scripts/gen/packages
